### ISSUE TITLE
Use JLL package made from BinaryBuilder.jl for dependency on CMINPACK

### ISSUE THREAD

**Issue by junyuan-chen** [sglyon/MINPACK.jl#11]
Thanks for the work on providing the wrapper!

Is there any plan of building a JLL package for the binary dependency instead of the current practice of placing the binaries on GitHub release? This is certainly the more sustainable way in the long run. But, the package seems to be out of maintenance for quite a while.

**Comment by sglyon** [comment]
I don't have a plan to do this, but would happily accept a pull request if somebody wanted to implement it.

Given that MINPACK is so stable, this package hasn't needed updates for a while. Not abandoned, just stable

**Comment by imciner2** [comment]
The library is now available from the general registry as `cminpack_jll`. It contains two libraries: `libcminpack` for double precision (`Float64`) and `libcminpacks` for single precision (`Float32`).
